### ISSUE TITLE
Refactor adapt functions

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-hardhat-plugin#156]
Refactor `adaptInputUtil` and `adaptComplexInput`
Same for `adaptOutputUtil` and `adaptComplexOutput`

The functions in each of the pairs are very similar, and common logic could be extracted, or one could use the other or something to reduce code duplication

**Comment by Dl-Vv** [comment]
Hey, I'd like to fix that issue. I just noticed that the name of the second function is `generateComplexOutput`, but the scope of the issue is still the same, right?

**Comment by ivpavici** [comment]
We plan to abandon the custom parsing and adaptation done in adapt.ts and rely on starknet.js.
