### ISSUE TITLE
AbiFormatError with Cairo1

### ISSUE THREAD

**Issue by gaetbout** [0xSpaceShard/starknet-hardhat-plugin#347]
I cloned:

https://github.com/0xSpaceShard/starknet-hardhat-example

And updated the cairo1 contract view to:
```rust
#[view]
fn get_balance(lama: felt252) -> felt252 {
     balance::read()
}
```

When running a simple test:
```ts
    before(async function () {
        account = await getPredeployedOZAccount();
        contractFactory = await starknet.getContractFactory("cairo1");
        await account.declare(contractFactory, { maxFee: 9e18 });
        contract = await account.deploy(contractFactory, { initial_balance });
    });
    it("should invoke", async () => {
        await account.invoke(contract, "increase_balance", {
            amount1: 20,
            amount2: 5
        });
        console.log(account.address);
        const resp = await contract.call("get_balance", { lama: 12 });
        expect(resp.response).to.be.eq(42);
    });
```

I'm running into: 
```shell
     StarknetPluginError: Could not perform call on get_balance.
Error: AbiFormatError: :1:5: Unexpected token Token('COLON', ':'). Expected one of: "*", ".", end of input.
core::felt252
    ^

Make sure to `invoke` and `estimateFee` through account, and `call` directly through contract.
```

**Comment by enitrat** [comment]
Could it be related to the fact that hardhat-plugin relies on an old version of Starknet.js?

**Comment by FabijanC** [comment]
@enitrat I don't think so, the old version of starknet.js is used for cryptography, which is not used in this case.

**Comment by FabijanC** [comment]
Is this reproducible using starknet.js or another client? Because we can't reproduce it by just relying on Starknet CLI.

@gaetbout

**Comment by gaetbout** [comment]
In this case, I didn't use starknet CLI but the example:
https://github.com/0xSpaceShard/starknet-hardhat-example

**Comment by FabijanC** [comment]
I meant: Can you compile, declare, deploy and invoke+call the contract you provided; all without relying on the hardhat plugin? If you are also getting this error without relying on the plugin, then it's not the plugin's fault.

**Comment by gaetbout** [comment]
If I use starknetjs to interact with devnet it works

**Comment by gaetbout** [comment]
In that case I use: 
 - nile to compile the cairo 0.x contracts
 - starknet-compile (json) + starknet-sierra-compile (casm) for 1.x contracts
Then I just do as explained here:
https://www.starknetjs.com/docs/guides/create_contract

**Comment by FabijanC** [comment]
Does it work if you use starknet.js with the artifacts generated by starknet-hardhat-plugin?

**Comment by FabijanC** [comment]
The cause of the problem has been diagnosed: Cairo 1 contracts don't actually require us to pass the ABI. The fix is on the way.
