### ISSUE TITLE
Refactor constructor checking

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-hardhat-plugin#367]
https://github.com/0xSpaceShard/starknet-hardhat-plugin/blob/18363cc4579895de69f0d2d11329893e9680754a/src/types/index.ts#L379

Plan:
- if constructors array is empty, we return a dummy always-false predicate 
- otherwise (meaning if length == 1, since we earlier checked if > 1), we return a predicate comparing with this only constructor name/selector 

We can also consider dropping the predicate approach, it's not like we'll have multiple predicates.

**Comment by remiroyc** [comment]
I'd be glad to handle this issue
