### ISSUE TITLE
Support Oracles

### ISSUE THREAD

**Issue by quentin-abei** [0xSpaceShard/starknet-hardhat-plugin#422]
For tests dev often uses mocks oracle in foundry or hardhat, How about finding a way to support oracle for writing test in starknet hardhat ?

**Comment by FabijanC** [comment]
Hi!

1. Do you use starknet-hardhat-plugin?
2. Do you have experience with mock oracles?
3. Can you provide resource links?

Thanks!

**Comment by ivpavici** [comment]
Oracles themselves provide mock contracts for their functionalities, not Hardhat itself...
https://hardhat.org/hardhat-runner/docs/supporter-guides/oracles
